# NumPy 

 - NumPy is fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on tehse data structures. 

In [10]:
import numpy as np

## creating arrays 
## 1D array 
 
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [11]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 cols


array([[1, 2, 3, 4, 5]])

In [12]:
#2D array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)
print(arr2)


(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]


## Arange Function:
  - this is printing every 2nd number in the range 0 - 10 and reshaping it to 5 rows and 1 column

In [ ]:

np.arange(0,10,2).reshape(5,1) 

array([[0],
       [2],
       [4],
       [6],
       [8]])

## Ones Function 
 - this is creating an array of 3 rows and 4 columns filled with ones

In [ ]:

np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Creating an Identity Matrix using Eye Funtion:
 - this created an identity matrix(diagonals are 1 and rest are 0) in parameter we give the size of the matrix

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Numpy Vectorized Operations:
 - Here element wise means the operation is being done between the elements at the same index that is 1 will be added/ subtracted to 10, simillarly 2 will be added/sub to 20 and so on.

In [15]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50,])

## Element Wise Addition 
print("Addition: ", arr1+arr2)

## Element Wise Subtraction
print("Subtraction: ", arr1-arr2)

## Element Wise Multiplication
print("Multiplication: ", arr1*arr2)

## Element Wise Division
print("Division: ", arr1/arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


## Universal Funtions:
- functions that are applied to the entire array , this is also done element wise

In [17]:
arr = np.array([2,3,4,5,6])

## Square Root
print("Square Root: ", np.sqrt(arr))

## Exponential
print("Exponential: ", np.exp(arr))

## Logarithm
print("Logarithm: ", np.log(arr))

## Sine
print("Sine: ", np.sin(arr))

Square Root:  [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential:  [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Logarithm:  [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
Sine:  [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


## Array Slicing and Indexing:

In [18]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
## Getting 1 index : [0][0]
print(arr[0][0])

1


In [ ]:
## Getting the elements 7,8,11,12 from the array
print(arr[1:, 2:]) 

print('------------------')

## Getting 6,7,10,11 from the array
print(arr[1:, 1:3])

[[ 7  8]
 [11 12]]
------------------
[[ 6  7]
 [10 11]]


In [25]:
## Modifying the Array Elements
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


## Statistical Methods:
- Mean
- Median 
- Standard Deviation 
- Variance


In [26]:
arr = np.array([1,2,3,4,5])

# Mean
print("Mean: ", np.mean(arr))

# Median
print('Median: ', np.median(arr))

## Standard Deviation
print('Standard Deviation: ', np.std(arr))

## Variance
print('Variance: ',np.var(arr))

Mean:  3.0
Median:  3.0
Standard Deviation:  1.4142135623730951
Variance:  2.0


In [27]:
## Normalization of our data

data = np.array([1,2,3,4,5])

# mean & standard deviation 

mean = np.mean(data)
st_dev = np.std(data)

# Normalization

normalized_data = (data-mean)/st_dev
print("Normalized Data: ", normalized_data)



Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
## Logical Operations 
# Returning the elements greater than 5 from the array

data = np.array([1,12,3,4,6,5,7,2,8,9,10,2])
print(data[data>5])
print(data>5) # This will return a boolean array where the condition is true. i.e the elements greater than 5 will be marked as True and the rest will be False.

[12  6  7  8  9 10]
[False  True False False  True False  True False  True  True  True False]
