# Numpy Practice Questions: 

## Array Creation and Manupilation using Numpy: 
1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [5]:
#1
# Creating a 5x5 array
import numpy as np
arr = np.random.randint(1,20, size = (5,5))
print(f'Original Array:\n {arr}')

#Replaccing the third row column elements with 1
arr[:, 2] = 1
print(f'Modified Array:\n {arr}')



Original Array:
 [[ 4 14 15 10  5]
 [ 7 10  9 18  3]
 [16 13 18  1  8]
 [15  5  9  7  2]
 [19 17 14 15  7]]
Modified Array:
 [[ 4 14  1 10  5]
 [ 7 10  1 18  3]
 [16 13  1  1  8]
 [15  5  1  7  2]
 [19 17  1 15  7]]


In [ ]:
#2
# Creating a 4x4 array with random nos
arr = np.random.randint(1,16, size= (4,4))
print(f'Original Array:\n {arr}')

# Replacing the diagonal elements with 0
np.fill_diagonal(arr, 0)
print(f'Modified Array:\n {arr}')

Original Array:
 [[13  2 11 10]
 [13  2  2  6]
 [12  2 15  9]
 [13 10  3  9]]
Modified Array:
 [[ 0  2 11 10]
 [13  0  2  6]
 [12  2  0  9]
 [13 10  3  0]]


## Array Indexing and Slicing: 
1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [13]:
#1
#Creating the Array 
arr = np.random.randint(1,36, size=(6,6))
print(f'Original Array:\n {arr}')

#sliced
print('----------------')
print(arr[2:5, 1:4])

Original Array:
 [[ 1  8 32 24 23  2]
 [31 21 29 24  3  8]
 [ 9 33  1 13 33 28]
 [11 23 15 28 34  8]
 [29 30  5 27  9 35]
 [35 16  4 31  5 16]]
----------------
[[33  1 13]
 [23 15 28]
 [30  5 27]]


In [14]:
# 2
# Creating a 5x5 array
arr = np.random.randint(1,20, size = (5,5))
print(f'Original Array:\n {arr}')

# Extracting the border elements
border_elements = np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print(f'Border Elements:\n {border_elements}')

Original Array:
 [[16  7 14 17 13]
 [11 17 12 11 17]
 [18 11 14  4  4]
 [13 17  8 13 12]
 [10  9 16 14 12]]
Border Elements:
 [16  7 14 17 13 10  9 16 14 12 11 18 13 17  4 12]


## Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
#1
arr1 = np.random.randint(1,10, size = (3,4))
arr2 = np.random.randint(1,15, size = (3,4))

# Operations:
print(f'Array 1:\n {arr1}')
print(f'Array 2:\n {arr2}')

print(f'Element_wise Sum :\n {arr1+arr2}')
print(f'Element_wise Product :\n {arr1*arr2}')
print(f'Element_wise Difference :\n {arr1-arr2}')
print(f'Element_wise Division :\n {arr1/arr2}')

Array 1:
 [[6 9 5 7]
 [9 1 9 9]
 [4 1 6 3]]
Array 2:
 [[12  4 11  1]
 [ 4  9  7  8]
 [ 5 14 10 11]]
Element_wise Sum :
 [[18 13 16  8]
 [13 10 16 17]
 [ 9 15 16 14]]
Element_wise Product :
 [[72 36 55  7]
 [36  9 63 72]
 [20 14 60 33]]
Element_wise Difference :
 [[ -6   5  -6   6]
 [  5  -8   2   1]
 [ -1 -13  -4  -8]]
Element_wise Division :
 [[0.5        2.25       0.45454545 7.        ]
 [2.25       0.11111111 1.28571429 1.125     ]
 [0.8        0.07142857 0.6        0.27272727]]


In [16]:
# 2
arr = np.random.randint(1,16, size = (4,4))
print(f'Original Array:\n {arr}')

# Row Wise Sum
print(f'Row-Wise Sum:\n {np.sum(arr, axis = 1)}')
print(f'column-wise sum:\n {np.sum(arr, axis = 0)}')

Original Array:
 [[ 8  3  1  6]
 [11  5 14  9]
 [ 6  5 12  7]
 [ 3  4  5 15]]
Row-Wise Sum:
 [18 39 30 27]
column-wise sum:
 [28 17 32 37]


## Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [18]:
arr1 = np.random.randint(1,10, size=(5,5))

mean = np.mean(arr1)
median = np.median(arr1)
std_dev = np.std(arr1)
variance = np.var(arr1)

print(f'Array:\n {arr1}')
print(f'Mean: {mean}')  
print(f'Median: {median}')
print(f'Standard Deviation: {std_dev}')
print(f'Variance: {variance}')

Array:
 [[5 6 4 4 4]
 [4 1 1 2 7]
 [1 7 7 5 8]
 [6 3 2 5 4]
 [8 9 8 2 7]]
Mean: 4.8
Median: 5.0
Standard Deviation: 2.4
Variance: 5.76
